### ISSUE TITLE
Why can't the marketplace be downloaded

### ISSUE THREAD

**Issue by fendo8888** [wizzdi/FlexiCore#10]
Why can't the marketplace be downloaded
![image](https://raw.githubusercontent.com/fendo8888/fendo/master/20210512233628.png)

https://support.wizzdi.com/

And this in the document UIComponents Is there a demo?

![image](https://raw.githubusercontent.com/fendo8888/fendo/master/20210512234046.png)

**Comment by asafbennatan** [comment]
hi @fendo8888 ,
regarding the marketplace we have not updated all the plugin entries over there . but you can easily get them from maven central:
https://search.maven.org/search?q=com.wizzdi , we will update the marketplace with the relevant link for each plugin soon.
as for demo of ui components this is not something we currently have , if required can you please open a feature request/ documentation enhancement ticket ?
Thanks.

**Comment by fendo8888** [comment]
Thank you

**Comment by asafbennatan** [comment]
closing this question , re-open or open a new ticket if required.
