### ISSUE TITLE
Does FlexiCore support mysql?

### ISSUE THREAD

**Issue by fendo8888** [wizzdi/FlexiCore#9]
Does FlexiCore support mysql?

**Comment by asafbennatan** [comment]
hi @fendo8888 ,
FlexiCore is a flexicore boot host implementation using postgresql.
if you'll have a look in the 5.0.0 and 5.1.0 branches you will see that actually there only code in the FlexiCore project is flyway migrations.
the entire code is inside flexicore modules such as 
https://github.com/wizzdi/flexicore-boot
https://github.com/wizzdi/flexicore-security-service
etc.
you can easily create a flexicore boot host by selecting only the required dependencies .
or more easily copy the entire pom from the FlexiCore project (branch 5.1.0 for example)
and replacing :
```
      <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
```
with the mysql jdbc dependencies:
```
  <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
```
as it is normally done with spring boot ( see https://zetcode.com/springboot/mysql/ for example).
more on flexicore modules and how to construct a flexicore boot host of your own (as opposed to using FlexiCore) can be seen here:
https://support.wizzdi.com/#flexicore-boot-host-application

**Comment by fendo8888** [comment]
Thank you

**Comment by asafbennatan** [comment]
closing this question , re-open or open a new ticket if required.
